/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as GpuCloudRouteImport } from './routes/gpu-cloud'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyProfileRouteImport } from './routes/company-profile'
import { Route as CaseRouteImport } from './routes/case'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AidcRouteImport } from './routes/aidc'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const GpuCloudRoute = GpuCloudRouteImport.update({
  id: '/gpu-cloud',
  path: '/gpu-cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyProfileRoute = CompanyProfileRouteImport.update({
  id: '/company-profile',
  path: '/company-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseRoute = CaseRouteImport.update({
  id: '/case',
  path: '/case',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AidcRoute = AidcRouteImport.update({
  id: '/aidc',
  path: '/aidc',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aidc': typeof AidcRoute
  '/approach': typeof ApproachRoute
  '/case': typeof CaseRoute
  '/company-profile': typeof CompanyProfileRoute
  '/contact': typeof ContactRoute
  '/gpu-cloud': typeof GpuCloudRoute
  '/insights': typeof InsightsRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aidc': typeof AidcRoute
  '/approach': typeof ApproachRoute
  '/case': typeof CaseRoute
  '/company-profile': typeof CompanyProfileRoute
  '/contact': typeof ContactRoute
  '/gpu-cloud': typeof GpuCloudRoute
  '/insights': typeof InsightsRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aidc': typeof AidcRoute
  '/approach': typeof ApproachRoute
  '/case': typeof CaseRoute
  '/company-profile': typeof CompanyProfileRoute
  '/contact': typeof ContactRoute
  '/gpu-cloud': typeof GpuCloudRoute
  '/insights': typeof InsightsRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/aidc'
    | '/approach'
    | '/case'
    | '/company-profile'
    | '/contact'
    | '/gpu-cloud'
    | '/insights'
    | '/services'
    | '/solutions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aidc'
    | '/approach'
    | '/case'
    | '/company-profile'
    | '/contact'
    | '/gpu-cloud'
    | '/insights'
    | '/services'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/aidc'
    | '/approach'
    | '/case'
    | '/company-profile'
    | '/contact'
    | '/gpu-cloud'
    | '/insights'
    | '/services'
    | '/solutions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AidcRoute: typeof AidcRoute
  ApproachRoute: typeof ApproachRoute
  CaseRoute: typeof CaseRoute
  CompanyProfileRoute: typeof CompanyProfileRoute
  ContactRoute: typeof ContactRoute
  GpuCloudRoute: typeof GpuCloudRoute
  InsightsRoute: typeof InsightsRoute
  ServicesRoute: typeof ServicesRoute
  SolutionsRoute: typeof SolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpu-cloud': {
      id: '/gpu-cloud'
      path: '/gpu-cloud'
      fullPath: '/gpu-cloud'
      preLoaderRoute: typeof GpuCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-profile': {
      id: '/company-profile'
      path: '/company-profile'
      fullPath: '/company-profile'
      preLoaderRoute: typeof CompanyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case': {
      id: '/case'
      path: '/case'
      fullPath: '/case'
      preLoaderRoute: typeof CaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aidc': {
      id: '/aidc'
      path: '/aidc'
      fullPath: '/aidc'
      preLoaderRoute: typeof AidcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AidcRoute: AidcRoute,
  ApproachRoute: ApproachRoute,
  CaseRoute: CaseRoute,
  CompanyProfileRoute: CompanyProfileRoute,
  ContactRoute: ContactRoute,
  GpuCloudRoute: GpuCloudRoute,
  InsightsRoute: InsightsRoute,
  ServicesRoute: ServicesRoute,
  SolutionsRoute: SolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
